name: Run checks

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: "Run ruff on Python 3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run ruff via nox
        run: |
          python -m pip install nox
          python -m nox -s format

  pyright:
    runs-on: ubuntu-latest
    name: "Run pyright via nox on Python 3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run pyright via nox
        run: |
          python -m pip install nox
          python -m nox -s pyright

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false

    name: Run pytest via nox on Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        python -m pip install nox
        python -m nox -s pytest
