name: Run checks

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: "Run isort and black on Python 3.10"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run black via nox
        run: |
          python -m pip install nox
          python -m nox -s format
  
  mypy:
    runs-on: ubuntu-latest
    name: "Run mypy via nox on Python 3.10"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run mypy via nox
        run: |
          python -m pip install nox
          python -m nox -s mypy
  
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
      fail-fast: false

    name: Run pytest via nox on Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        python -m pip install nox
        python -m nox -s pytest